// <auto-generated />
namespace MovieRentalStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newChange052020172 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newChange052020172));
        
        string IMigrationMetadata.Id
        {
            get { return "201705201719522_newChange052020172"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
