// <auto-generated />
namespace MovieRentalStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_Genre_ReleaseDate_AddedDate_MovieTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Genre_ReleaseDate_AddedDate_MovieTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201705200129173_Add_Genre_ReleaseDate_AddedDate_MovieTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
